// code3ui/src/App.tsx
/* ═══════════════════════════════════════════════════════════════════
   code3ui — App Root
   ═══════════════════════════════════════════════════════════════════ */
import React from 'react'
import Code3UISurface from './views/surfaces/code3ui/Code3UISurface'

const App: React.FC = () => {
  return <Code3UISurface />
}

export default App

// code3ui/src/App.vue
<template>
  <Code3UISurface />
</template>

<script setup lang="ts">
import Code3UISurface from './views/surfaces/code3ui/Code3UISurface.vue'
</script>

<style>
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html, body {
  height: 100%;
  overflow: hidden;
}

#app {
  height: 100%;
}
</style>
