// code4ui/src/views/surfaces/code4ui/Code4UIChatSheet.vue
<template>
  <aside class="code4ui-chat" :class="{ open: store.chatOpen }">
    <!-- Chat Header -->
    <div class="chat-header">
      <h3 class="chat-title">
        <span class="material-symbols-outlined chat-title-icon">chat</span>
        Assistant
      </h3>
      <button class="chat-close-btn" @click="store.toggleChat">
        <span class="material-symbols-outlined chat-close-icon">close</span>
      </button>
    </div>

    <!-- Messages -->
    <div class="chat-messages" ref="messagesContainer">
      <div v-if="store.chatMessages.length === 0" class="chat-empty">
        <span class="material-symbols-outlined chat-empty-icon">smart_toy</span>
        <p>Ask me anything about your workspace, wireframes, or system status.</p>
      </div>
      <div
        v-for="(msg, idx) in store.chatMessages"
        :key="idx"
        class="chat-message"
        :class="`chat-message--${msg.role}`"
      >
        <div class="chat-message-avatar">
          <span class="material-symbols-outlined chat-avatar-icon">{{ msg.role === 'user' ? 'person' : 'smart_toy' }}</span>
        </div>
        <div class="chat-message-content">{{ msg.content }}</div>
      </div>
    </div>

    <!-- Input -->
    <div class="chat-input-area">
      <div class="chat-input-wrapper">
        <input
          v-model="inputText"
          type="text"
          class="chat-input"
          placeholder="Type a message..."
          @keydown.enter="sendMessage"
        />
        <button class="chat-send-btn" @click="sendMessage" :disabled="!inputText.trim()">
          <span class="material-symbols-outlined chat-send-icon">send</span>
        </button>
      </div>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { ref, nextTick } from 'vue'
import { useCode4UIStore } from './stores/code4UIStore'

const store = useCode4UIStore()
const inputText = ref('')
const messagesContainer = ref<HTMLElement | null>(null)

async function sendMessage() {
  const text = inputText.value.trim()
  if (!text) return

  store.addChatMessage('user', text)
  inputText.value = ''

  setTimeout(() => {
    store.addChatMessage('assistant', `I received your message: "${text}". This is a simulated response — wire to an actual AI backend for real functionality.`)
    scrollToBottom()
  }, 500)

  await nextTick()
  scrollToBottom()
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
  }
}
</script>

<style scoped>
.code4ui-chat {
  width: 0;
  min-width: 0;
  overflow: hidden;
  background: var(--usx-color-surface);
  border-left: 1px dashed var(--usx-color-outline);
  display: flex;
  flex-direction: column;
  transition: width 0.25s ease, min-width 0.25s ease;
  font-size: var(--code4ui-font-size);
}

.code4ui-chat.open {
  width: var(--code4ui-chat-width);
  min-width: var(--code4ui-chat-width);
}

.chat-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  border-bottom: 1px dashed var(--usx-color-outline);
  flex-shrink: 0;
}

.chat-title {
  font-size: calc(var(--code4ui-font-size) * 0.9);
  font-weight: 600;
  color: var(--usx-color-on-surface);
  margin: 0;
  display: flex;
  align-items: center;
  gap: 6px;
}

.chat-title-icon,
.chat-close-icon,
.chat-avatar-icon,
.chat-send-icon {
  font-size: calc(var(--code4ui-font-size) * 1.1) !important;
}

.chat-close-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border: 1px dashed var(--usx-color-outline);
  border-radius: var(--md-sys-shape-corner-extra-small);
  background: transparent;
  color: var(--usx-color-on-surface-variant);
  cursor: pointer;
  transition: all 0.15s;
}

.chat-close-btn:hover {
  background: var(--usx-color-surface-variant);
  color: var(--usx-color-on-surface);
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 12px 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.chat-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  text-align: center;
  color: var(--usx-color-on-surface-variant);
  font-size: calc(var(--code4ui-font-size) * 0.85);
  padding: 24px;
  gap: 12px;
}

.chat-empty-icon {
  font-size: 48px;
}

.chat-message {
  display: flex;
  gap: 8px;
  max-width: 100%;
}

.chat-message--user {
  flex-direction: row-reverse;
}

.chat-message-avatar {
  flex-shrink: 0;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: var(--usx-color-surface-variant);
  border: 1px dashed var(--usx-color-outline);
}

.chat-message-content {
  padding: 8px 12px;
  border-radius: var(--md-sys-shape-corner-small);
  font-size: calc(var(--code4ui-font-size) * 0.85);
  line-height: 1.4;
  max-width: 80%;
  word-wrap: break-word;
  border: 1px dashed var(--usx-color-outline);
}

.chat-message--user .chat-message-content {
  background: var(--usx-color-primary);
  color: var(--usx-color-on-primary);
  border-style: solid;
}

.chat-message--assistant .chat-message-content {
  background: var(--usx-color-surface-variant);
  color: var(--usx-color-on-surface);
}

.chat-input-area {
  padding: 12px 16px;
  border-top: 1px dashed var(--usx-color-outline);
  flex-shrink: 0;
}

.chat-input-wrapper {
  display: flex;
  gap: 8px;
  align-items: center;
}

.chat-input {
  flex: 1;
  padding: 8px 12px;
  border: 1px dashed var(--usx-color-outline);
  border-radius: var(--md-sys-shape-corner-full);
  background: var(--usx-color-surface-variant);
  color: var(--usx-color-on-surface);
  font-family: inherit;
  font-size: calc(var(--code4ui-font-size) * 0.85);
  outline: none;
  transition: border-color 0.15s;
}

.chat-input:focus {
  border-color: var(--usx-color-primary);
  border-style: solid;
}

.chat-input::placeholder {
  color: var(--usx-color-on-surface-variant);
}

.chat-send-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border: 1px dashed var(--usx-color-outline);
  border-radius: 50%;
  background: var(--usx-color-primary);
  color: var(--usx-color-on-primary);
  cursor: pointer;
  transition: all 0.15s;
  flex-shrink: 0;
}

.chat-send-btn:hover:not(:disabled) {
  opacity: 0.9;
}

.chat-send-btn:disabled {
  opacity: 0.38;
  cursor: not-allowed;
}

.chat-messages::-webkit-scrollbar {
  width: 4px;
}

.chat-messages::-webkit-scrollbar-track {
  background: transparent;
}

.chat-messages::-webkit-scrollbar-thumb {
  background: var(--usx-color-outline);
  border-radius: 2px;
}
</style>

// code4ui/src/views/surfaces/code4ui/Code4UIChatSheet.tsx
/* ═══════════════════════════════════════════════════════════════════
   code4ui ChatSheet — Wireframe Surface Chat Panel
   ═══════════════════════════════════════════════════════════════════ */

import React, { useState, useRef, useEffect } from 'react'
import { useCode4UIStore } from './stores/code4UIStore'

export default function Code4UIChatSheet() {
  const store = useCode4UIStore()
  const [inputText, setInputText] = useState('')
  const messagesContainerRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = () => {
    if (messagesContainerRef.current) {
      messagesContainerRef.current.scrollTop = messagesContainerRef.current.scrollHeight
    }
  }

  useEffect(() => {
    scrollToBottom()
  }, [store.chatMessages])

  const sendMessage = () => {
    const text = inputText.trim()
    if (!text) return

    store.addChatMessage('user', text)
    setInputText('')

    setTimeout(() => {
      store.addChatMessage('assistant', `I received your message: "${text}". This is a simulated response — wire to an actual AI backend for real functionality.`)
    }, 500)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <aside className={`code4ui-chat ${store.chatOpen ? 'open' : ''}`}>
      {/* Chat Header */}
      <div className="chat-header">
        <h3 className="chat-title">
          <span className="material-symbols-outlined chat-title-icon">chat</span>
          Assistant
        </h3>
        <button className="chat-close-btn" onClick={store.toggleChat}>
          <span className="material-symbols-outlined chat-close-icon">close</span>
        </button>
      </div>

      {/* Messages */}
      <div className="chat-messages" ref={messagesContainerRef}>
        {store.chatMessages.length === 0 ? (
          <div className="chat-empty">
            <span className="material-symbols-outlined chat-empty-icon">smart_toy</span>
            <p>Ask me anything about your workspace, wireframes, or system status.</p>
          </div>
        ) : (
          store.chatMessages.map((msg, idx) => (
            <div key={idx} className={`chat-message chat-message--${msg.role}`}>
              <div className="chat-message-avatar">
                <span className="material-symbols-outlined chat-avatar-icon">
                  {msg.role === 'user' ? 'person' : 'smart_toy'}
                </span>
              </div>
              <div className="chat-message-content">{msg.content}</div>
            </div>
          ))
        )}
      </div>

      {/* Input */}
      <div className="chat-input-area">
        <div className="chat-input-wrapper">
          <input
            type="text"
            className="chat-input"
            placeholder="Type a message..."
            value={inputText}
            onChange={e => setInputText(e.target.value)}
            onKeyDown={handleKeyDown}
          />
          <button
            className="chat-send-btn"
            onClick={sendMessage}
            disabled={!inputText.trim()}
          >
            <span className="material-symbols-outlined chat-send-icon">send</span>
          </button>
        </div>
      </div>
    </aside>
  )
}
